project:
  type: website

website:
  title: Sentiment Analysis on Tech-based Stocks
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO526-DataViz/project-01
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd
    logo: images\feature_finders.jpeg
  favicon:  images\feature_finders.jpeg

format:
  html:
    theme: lux
    toc: true

execute:
  freeze: auto
